[versions]
kotlin = "2.1.0"

[libraries]
jansi = "org.fusesource.jansi:jansi:2.4.1"
kotest = "io.kotest:kotest-runner-junit5-jvm:5.9.1"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "11.6.1" }
